version: '3.8'
services:
  db:
    image: postgres:15
    container_name: users_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: usradmin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usradmin -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
